---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: cloudflare-dyndns

env:
  - CI_COMMIT_SHA={{ .FullCommit }}
  - CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/x86_64-linux-gnu-gcc
  - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc
  - CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=/usr/bin/x86_64-linux-musl-gcc
  - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=/opt/dyne/gcc-musl/bin/aarch64-linux-musl-gcc
  - PKG_CONFIG_ALLOW_CROSS=true

before:
  hooks:
    - cargo fetch --locked

builds:
  - id: dynamic
    builder: rust
    binary: cloudflare-dyndns
    tool: cargo
    command: build
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    env:
      - >-
        {{- if eq .Target "aarch64-unknown-linux-gnu" }}
          PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
        {{- else if eq .Target "x86_64-unknown-linux-gnu" }}
          PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-gnu/pkgconfig
        {{- end }}
  - id: static
    builder: rust
    binary: cloudflare-dyndns
    tool: cargo
    command: build
    flags:
      - --release
      - --features=native-tls-vendored
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
    env:
      - RUSTFLAGS=-C target-feature=+crt-static -C relocation-model=static
      - >-
        {{- if eq .Target "aarch64-unknown-linux-musl" }}
          PKG_CONFIG_PATH=/opt/dyne/aarch64-linux-musl/lib/pkgconfig
        {{- else if eq .Target "x86_64-unknown-linux-musl" }}
          PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-musl/pkgconfig
        {{- end }}
  - id: compressed
    builder: rust
    binary: cloudflare-dyndns
    tool: cargo
    command: build
    flags:
      - --release
      - --features=native-tls-vendored
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
    env:
      - RUSTFLAGS=-C target-feature=+crt-static -C relocation-model=static
      - >-
        {{- if eq .Target "aarch64-unknown-linux-musl" }}
          PKG_CONFIG_PATH=/opt/dyne/aarch64-linux-musl/lib/pkgconfig
        {{- else if eq .Target "x86_64-unknown-linux-musl" }}
          PKG_CONFIG_LIBDIR=/usr/lib/x86_64-linux-musl/pkgconfig
        {{- end }}

upx:
  - enabled: true
    ids:
      - compressed
    compress: "9"

archives:
  - formats: ["binary"]

nfpms:
  - id: openwrt
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_openwrt-{{ .Arch }}"
    ids:
      - static
    maintainer: Heathcliff <heathcliff@heathcliff.eu>
    description: DDNS client for cloudflare
    license: Apache 2.0
    formats:
      - apk
    dependencies:
      - ca-bundle
      - "!cloudflare-dyndns-compressed"
    bindir: /usr/sbin
    contents:
      - src: packages/openwrt/etc-config
        dst: /etc/config/cloudflare-dyndns
      - src: packages/openwrt/init-d.sh
        dst: /etc/init.d/cloudflare-dyndns
        file_info:
          mode: 0755
      - src: packages/openwrt/config.yaml
        dst: /etc/cloudflare-dyndns/config.yaml
    scripts:
      postinstall: packages/openwrt/postinstall.sh
      preremove: packages/openwrt/preremove.sh
  - id: openwrt-compressed
    package_name: "{{ .ProjectName }}-compressed"
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_openwrt-{{ .Arch }}"
    ids:
      - compressed
    maintainer: Heathcliff <heathcliff@heathcliff.eu>
    description: DDNS client for cloudflare
    license: Apache 2.0
    formats:
      - apk
    dependencies:
      - ca-bundle
      - "!cloudflare-dyndns"
    bindir: /usr/sbin
    contents:
      - src: packages/openwrt/etc-config
        dst: /etc/config/cloudflare-dyndns
      - src: packages/openwrt/init-d.sh
        dst: /etc/init.d/cloudflare-dyndns
        file_info:
          mode: 0755
      - src: packages/openwrt/config.yaml
        dst: /etc/cloudflare-dyndns/config.yaml
    scripts:
      postinstall: packages/openwrt/postinstall.sh
      preremove: packages/openwrt/preremove.sh
  - id: linux
    package_name: "{{ .ProjectName }}"
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_linux-{{ .Arch }}"
    ids:
      - dynamic
    maintainer: Heathcliff <heathcliff@heathcliff.eu>
    description: DynDNS client or relay server for cloudflare, implemented in rust.
    license: Apache-2.0
    homepage: https://github.com/heathcliff26/{{ .ProjectName }}
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - dst: /usr/share/licenses/{{ .ProjectName }}
        type: dir
      - dst: /usr/share/doc/{{ .ProjectName }}
        type: dir
      - src: LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE
      - src: README.md
        dst: /usr/share/doc/{{ .ProjectName }}/README.md
      - src: tools/{{ .ProjectName }}-client.service
        dst: /usr/lib/systemd/system/{{ .ProjectName }}-client.service
      - src: tools/{{ .ProjectName }}-relay.service
        dst: /usr/lib/systemd/system/{{ .ProjectName }}-relay.service
      - src: tools/{{ .ProjectName }}-server.service
        dst: /usr/lib/systemd/system/{{ .ProjectName }}-server.service
      - dst: /etc/{{ .ProjectName }}
        type: dir
      - src: examples/example-config.yaml
        dst: /etc/{{ .ProjectName }}/config.yaml
        type: config|noreplace
      - src: io.github.heathcliff26.{{ .ProjectName }}.metainfo.xml
        dst: /usr/share/metainfo/io.github.heathcliff26.{{ .ProjectName }}.metainfo.xml
    scripts:
      postinstall: "packages/linux/postinstall.sh"
      preremove: "packages/linux/preremove.sh"
      postremove: "packages/linux/postremove.sh"
    rpm:
      summary: DynDNS client or relay server for cloudflare

changelog:
  disable: true
release:
  disable: true
