type: client
config:
  client:
    token: "secret-token"
    proxy: true
    domains:
      - "${NODE_NAME}.heathcliff26.net"
    interval: 300
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
