type: client
config:
  client:
    proxy: true
    domains:
      - "${NODE_NAME}.heathcliff26.net"
    interval: 300
env:
  - name: CLOUDFLARE_DYNDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: token
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
