---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
data:
  config.yaml: |
    client:
      token: "${CLOUDFLARE_DYNDNS_TOKEN}"
      proxy: true
      domains:
        - "${NODE_NAME}.example.com"
      interval: "5m"
      endpoint: "https://dyndns.example.com/"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
type: Opaque
data:
  token: "this-could-be-your-token"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ddclient
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ddclient
spec:
  selector:
    matchLabels:
      app: ddclient
  template:
    metadata:
      labels:
        app: ddclient
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: cloudflare-dyndns
        image: ghcr.io/heathcliff26/cloudflare-dyndns:latest
        args: ["relay", "--config", "/config/config.yaml", "--env"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CLOUDFLARE_DYNDNS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: token
        volumeMounts:
          - name: ddclient-config
            mountPath: /config/config.yaml
            subPath: config.yaml
      volumes:
        - name: ddclient-config
          configMap:
            name: ddclient-config
            items:
                - key: config.yaml
                  path: config.yaml
