---
name: CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release build"
        type: boolean
        default: false
        required: false
      dry-run:
        description: "Do not push image"
        type: boolean
        default: false
        required: false
      latest:
        description: "Tag latest"
        type: boolean
        default: false
        required: false
  workflow_call:
    inputs:
      release:
        description: "Release build"
        type: boolean
        default: false
        required: false
      dry-run:
        description: "Do not push image"
        type: boolean
        default: false
        required: false
      latest:
        description: "Tag latest"
        type: boolean
        default: false
        required: false
  push:
    branches: ["main"]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - "tests/**"
      - "Dockerfile"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  extract-version:
    uses: heathcliff26/ci/.github/workflows/cargo-version.yaml@main
    permissions:
      contents: read

  doc:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make doc"

  lint:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make lint"

  test:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make test"

  validate:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make validate"

  e2e:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make test-e2e"

  build-artifacts:
    uses: heathcliff26/ci/.github/workflows/run-script.yaml@main
    permissions:
      contents: read
    with:
      cmd: "make release"
      artifact: "dist/*"
      artifact-name: "cloudflare-dyndns"
    secrets: inherit

  build-image:
    uses: heathcliff26/ci/.github/workflows/build-container.yaml@main
    needs:
      - extract-version
      - doc
      - lint
      - test
      - validate
      - e2e
      - build-artifacts
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: Dockerfile
      tag: "${{ inputs.release && needs.extract-version.outputs.version || 'rolling' }}"
      tags: "${{ inputs.latest == true && 'type=raw,value=latest' || '' }}"
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' || inputs.dry-run == 'true' }}
    secrets: inherit

  push-helm:
    uses: heathcliff26/ci/.github/workflows/push-helm-chart.yaml@main
    if: ${{ inputs.release }}
    needs:
      - extract-version
      - doc
      - lint
      - test
      - validate
      - e2e
      - build-artifacts
    permissions:
      contents: read
      packages: write
    with:
      tag: "${{ inputs.release && needs.extract-version.outputs.version || 'rolling' }}"
      dry-run: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' || inputs.dry-run == 'true' }}
    secrets: inherit
